// Run with: node --test test/id-patterns.test.mjs
// The identifier patterns the extension accepts, each tied to the clawser value it validates.
// The extension never receives a browser-task DEFINITION id (a synced routine carries no action
// payload; it only learns the routine id and an informational actionType), so the stricter
// definition-id pattern does not apply to anything the extension validates.
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { loadBackground } from './_load-background.mjs';

const KEY = 'background_routine_state';
const cron = (id, extra = {}) => ({ id, name: id, enabled: true, trigger: { type: 'cron', cron: '* * * * *' }, actionType: 'prompt', ...extra });
const synced = async (routines, opts) => { const b = loadBackground(); await b.pageSync(routines, opts); return (b.idbStore.get(KEY) || []).map((r) => r.id); };

describe('ROUTINE_ID_RE: ids of routines synced from the page', () => {
  // Counterpart: SAFE_ID in clawser web/clawser-extension-routine-bridge.js, which filters what is sent.
  // Generated by clawser: `routine_<n>` (clawser-routines.js) and `btask_<definitionId>` (clawser-btask-monitor.mjs).
  const good = ['routine_1', 'routine_12345', 'btask_def_abc-123', `btask_${'a'.repeat(80)}`, 'a', 'x'.repeat(100), 'user.defined:id-1_ok'];
  const bad = ['', 'x'.repeat(101), 'has space', 'a/b', 'a\\b', 'a$b', 'a;b', '../x', 'a\nb', 'é', 'a*', 'a?', '<b>'];
  for (const id of good) it(`accepts ${JSON.stringify(id.length > 30 ? id.slice(0, 12) + '...' : id)}`, async () => assert.deepEqual(await synced([cron(id)]), [id]));
  for (const id of bad) it(`rejects ${JSON.stringify(id.length > 30 ? id.slice(0, 12) + '...' : id)}`, async () => assert.deepEqual(await synced([cron(id)]), []));
  it('rejects non-string ids', async () => {
    for (const id of [1, null, undefined, {}, []]) assert.deepEqual(await synced([cron(id)]), []);
  });
});

describe('WORKSPACE_ID_RE: workspace ids', () => {
  // Counterpart: clawser's workspace id (docs/BROWSER-TASKS.md), /^[A-Za-z0-9_-]{1,80}$/.
  // Clawser generates `ws_<base36>_<4 hex>` and 'default'.
  const good = ['default', 'ws_mf3k2a_9c1d', 'a', 'w'.repeat(80), 'A-b_9'];
  const bad = ['', 'w'.repeat(81), 'a.b', 'a:b', 'a b', 'a/b', 'é', '../x', 5, null, {}];
  for (const wsId of good) it(`routines_sync accepts ${wsId}`, async () => {
    const b = loadBackground();
    await b.pageSync([cron('r')], { wsId });
    assert.equal(b.idbStore.get(KEY).length, 1);
  });
  for (const wsId of bad) it(`routines_sync rejects ${JSON.stringify(wsId)}`, async () => {
    const b = loadBackground();
    await b.pageSync([cron('r')], { wsId });
    assert.equal(b.idbStore.get(KEY), undefined);
  });

  it('workspace_ready with an invalid wsId is treated as having no wsId (and is not persisted)', async () => {
    for (const wsId of ['a.b', 'w'.repeat(81), 5]) {
      const b = loadBackground();
      b.notify('workspace_ready', { wsId }, { tab: { id: 5, url: 'https://clawser.erisera.com/' } });
      await new Promise((r) => setTimeout(r, 15));
      assert.equal(b.localStore.workspaceRef?.wsId ?? null, null, String(wsId));
    }
  });

  it('routine_failures refuses an invalid wsId', async () => {
    const b = loadBackground();
    const sender = { tab: { id: 5, url: 'https://clawser.erisera.com/' } };
    for (const wsId of ['a.b', 'w'.repeat(81)]) {
      b.notify('workspace_ready', { wsId }, sender);
      assert.ok((await b.send('routine_failures', { wsId, since: 0 }, sender)).error, wsId);
    }
  });

  it('a persisted workspace reference with an invalid wsId is ignored on cold start', async () => {
    const created = [];
    const b = loadBackground({ tabs: { create: async (o) => { created.push(o); return { id: 1 }; }, get: async () => { throw new Error('x'); }, query: async () => [] } },
      { storage: { workspaceRef: { wsId: 'a.b', url: 'https://clawser.erisera.com/', lastSeen: 1 } } });
    b.idbStore.set(KEY, [{ id: 'r', name: 'r', enabled: true, trigger: { type: 'cron', cron: '* * * * *' }, state: {} }]);
    await b.fireAlarm();
    assert.deepEqual(created, []);
  });
});

describe('DEFINITION_ID_RE: browser-task definition ids', () => {
  // Counterpart: ID_RE in clawser web/clawser-btask-store.mjs. Shared contract: /^[A-Za-z0-9_-]{1,80}$/.
  it('isDefinitionId implements the shared pattern', () => {
    const { sandbox } = loadBackground();
    for (const good of ['def_1-A', 'a', 'x'.repeat(80)]) assert.equal(sandbox.isDefinitionId(good), true, good);
    for (const bad of ['', 'a.b', 'a:b', 'a b', 'x'.repeat(81), 5, null]) assert.equal(sandbox.isDefinitionId(bad), false, String(bad));
  });

  it('a definition id never enters the extension: extra fields on a synced routine are not stored', async () => {
    const b = loadBackground();
    await b.pageSync([cron('btask_d1', { actionType: 'btask_monitor', definitionId: 'd1', action: { type: 'btask_monitor', definitionId: 'd1' } })]);
    const r = b.idbStore.get(KEY)[0];
    assert.equal('definitionId' in r, false);
    assert.deepEqual(r.action, { type: 'btask_monitor' });
  });

  it('a routine in the reserved btask_ namespace must embed a valid definition id', async () => {
    assert.deepEqual(await synced([cron('btask_d1'), cron('btask_a.b'), cron('btask_'), cron(`btask_${'a'.repeat(81)}`), cron('notbtask_a.b')]), ['btask_d1', 'notbtask_a.b']);
  });

  it('isBtaskRoutineId is `btask_` plus a valid definition id', () => {
    const { sandbox } = loadBackground();
    assert.equal(sandbox.isBtaskRoutineId('btask_def_1'), true);
    assert.equal(sandbox.isBtaskRoutineId(`btask_${'a'.repeat(80)}`), true);
    for (const bad of ['btask_', 'btask_a.b', `btask_${'a'.repeat(81)}`, 'routine_1', 'xbtask_a']) assert.equal(sandbox.isBtaskRoutineId(bad), false, bad);
  });
});
